### PR TITLE
Add Panel control for JciHitachi AC devices

### PR DESCRIPTION
**Pull request by amigcamel**
Panel control allows users to manipulate the brightness of the display.

### CODE REVIEW

**Comment by amigcamel** [comment]
@qqaatw 
Tested on my RAS-22NT, and the attached is the code executed in conjunction with the official app in practical scenarios.
Related issue: [PR#70的亮度控制是否僅能給除濕機使用？](https://github.com/qqaatw/JciHitachiHA/issues/71)

https://github.com/qqaatw/LibJciHitachi/assets/7016634/0529d1bb-3b73-4bca-8003-bd242a0c631e

**Comment by qqaatw** [comment]
Can you rebase please?

**Comment by amigcamel** [comment]
Please check again. Give me a heads up if I miss anything, thanks.

**Comment by qqaatw** [comment]
FYI, the PR is included in the latest release now.

**Pull request merged**
